ExternalCommands:
	gcc lsimplement.c -o lsimplement
	gcc rmimplement.c -o rmimplement
	gcc catimplement.c -o catimplement
	gcc dateimplement.c -o dateimplement
	gcc mkdirimplement.c -o mkdirimplement
	gcc -pthread ExternalCommands.c -o ExternalCommands
	./ExternalCommands

	

